in:
  type: file
  path_prefix: ./logs/commits-
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    skip_header_lines: 0
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: repo, type: string}
    - {name: sha, type: string}
    - {name: 'message', type: string}
out: {type: stdout}
