version: '3'
services: 
  embulk:
    build: .
    env_file: .env
    volumes:
      - .:/work
  mysql:
    image: mysql:5.6.35
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
volumes:
  mysql-data:
    driver: local
